version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: webman-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8787:8787"
    depends_on:
      - redis
      - mysql
    networks:
      - webman-network
    env_file:
      - .env

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: webman-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root       
      MYSQL_DATABASE: webman_db          
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - webman-network
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - webman-network

  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - webman-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webman-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - webman-network

volumes:
  mysql-data:
  redis-data:
  es_data:
networks:
  webman-network:
    driver: bridge